version: "3.2"
services:
  flip-eth-a:
    build: .
    image: makerdao/auction-keeper
    container_name: flip-eth-a
    working_dir: /opt/keeper/flip-eth-a/
    volumes:
      - $PWD/secrets:/opt/keeper/secrets
      - $PWD/env/:/opt/keeper/env/
      - $PWD/flip/eth-a/:/opt/keeper/flip-eth-a/
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    command: ./flip-eth-a.sh model-eth.sh
  flip-bat-a:
    build: .
    image: makerdao/auction-keeper
    container_name: flip-bat-a
    working_dir: /opt/keeper/flip-bat-a/
    volumes:
      - $PWD/secrets:/opt/keeper/secrets
      - $PWD/env/:/opt/keeper/env/
      - $PWD/flip/bat-a/:/opt/keeper/flip-bat-a/
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    command: ./flip-bat-a.sh model-bat.sh
  flip-usdc-a:
    build: .
    image: makerdao/auction-keeper
    container_name: flip-usdc-a
    working_dir: /opt/keeper/flip-usdc-a/
    volumes:
      - $PWD/secrets:/opt/keeper/secrets
      - $PWD/env/:/opt/keeper/env/
      - $PWD/flip/usdc-a/:/opt/keeper/flip-usdc-a/
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    command: ./flip-usdc-a.sh model-usdc.sh
  flip-usdc-b:
    build: .
    image: makerdao/auction-keeper
    container_name: flip-usdc-b
    working_dir: /opt/keeper/flip-usdc-b/
    volumes:
      - $PWD/secrets:/opt/keeper/secrets
      - $PWD/env/:/opt/keeper/env/
      - $PWD/flip/usdc-b/:/opt/keeper/flip-usdc-b/
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    command: ./flip-usdc-b.sh model-usdc.sh
  flip-wbtc-a:
    build: .
    image: makerdao/auction-keeper
    container_name: flip-wbtc-a
    working_dir: /opt/keeper/flip-wbtc-a/
    volumes:
      - $PWD/secrets:/opt/keeper/secrets
      - $PWD/env/:/opt/keeper/env/
      - $PWD/flip/wbtc-a/:/opt/keeper/flip-wbtc-a/
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    command: ./flip-wbtc-a.sh model-wbtc.sh
  flip-tusd-a:
    build: .
    image: makerdao/auction-keeper
    container_name: flip-tusd-a
    working_dir: /opt/keeper/flip-tusd-a/
    volumes:
      - $PWD/secrets:/opt/keeper/secrets
      - $PWD/env/:/opt/keeper/env/
      - $PWD/flip/tusd-a/:/opt/keeper/flip-tusd-a/
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    command: ./flip-tusd-a.sh model-tusd.sh
  flop:
    build: .
    image: makerdao/auction-keeper
    container_name: flop
    working_dir: /opt/keeper/flop/
    volumes:
      - $PWD/secrets:/opt/keeper/secrets
      - $PWD/env/:/opt/keeper/env/
      - $PWD/flop/:/opt/keeper/flop/
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    command: ./flop.sh model-mkr.sh
